### ISSUE TITLE
What happens when a robot touches a wall and doesn't move?

### ISSUE THREAD

**Issue by liwenshulws** [zerosansan/td3_ddpg_sac_dqn_qlearning_sarsa_mobile_robot_navigation#1]
Hello, excuse me. I would like to ask how to resolve this error

[INFO] [1694695746.578410, 453.297000]: Collision!!
Traceback (most recent call last):
  File "/home/robot/catkin_ws/src/turtlebot3_rl_sim/src/start_td3_training.py", line 140, in <module>
    social_safety_score = env.get_social_safety_violation_status(step + 1)
AttributeError: Env instance has no attribute 'get_social_safety_violation_status'
[INFO] [1694695746.740809, 453.443000]: Stopping TurtleBot
[turtlebot3_td3-1] process has died [pid 2675, exit code 1, cmd /home/robot/catkin_ws/src/turtlebot3_rl_sim/src/start_td3_training.py __name:=turtlebot3_td3 __log:=/home/robot/.ros/log/933e1d78-52fb-11ee-88b7-000c29188fcd/turtlebot3_td3-1.log].
log file: /home/robot/.ros/log/933e1d78-52fb-11ee-88b7-000c29188fcd/turtlebot3_td3-1*.log

**Comment by zerosansan** [comment]
Hello. If you look at Line #14 of the `start_td3_training.py` file. It imports the environment from `environment_stage_1_original` which contains no function of 'get_social_safety_violation_status'. So, you just have to import the environment from `environment_stage_1_nobonus` and it should work just fine.

**Comment by liwenshulws** [comment]
Thank you. Although the error was resolved, the robot still encountered a wall that did not move or collided with an obstacle during the training process. Could you please take a look at what happened?

**Comment by zerosansan** [comment]
It could be that the turtlebot3's minimum laserscan range is too low for it to reliably detect wall objects. You can set it at a higher value (e.g. 0.12) and retrain the model.

The config files are here: turtlebot3_rl_sim/src/configs/turtlebot3_world.yaml. It's on Line #8 (`min_scan_range: 0.105`)

**Comment by liwenshulws** [comment]
Hello, I'm really sorry, but now there's a new error. As soon as the car encounters a green obstacle, it stops one round of training and keeps getting stuck in the starting part. After stopping the training, a new error message occurs, as follows:
[WARN] [1694762392.874953, 0.122000]: EPISODE: 9 | STEP: 1
DON: MINIMUM RANGE
[INFO] [1694762393.042830, 0.284000]: Collision!!
[INFO] [1694762393.044288, 0.285000]: Stopping TurtleBot
^C [turbobot3_td3-1] killing on exit
[INFO] [1694762393.206842, 0.440000]: Stopping TurtleBot
[WARN] [1694762394.355640, 1.441000]: DONE
('EPISODE REWARD: ', -199)
('EPISODE STEP: ', 1)
('EPISODE SUCCESS: ', False)
('EPISODE FAILURE: ', True)
[WARN] [1694762394.357341, 1.441000]: EPISODE: 10
Traceback (most recent call last):
File "/home/robot/catkin_ws/src/tourlebot3_rl_sim/src/start_td3_training. py", line 110, in<module>
Observation=env. reset()
File "/home/robot/catkin_ws/src/tourlebot3_rl_sim/src/environment_stage1_original. py", line 464, in reset
Rospy.wait_ For_ Service ('gazebo/reset_simulation ')
File "/opt/ros/media/lib/python2.7/dist packages/rose/impl/tcpros_service. py", line 166, in wait_ For_ Service
Raise ROSInterruptException ("rose shutdown")
Rospy. exceptions. ROSInterruptException: rospy shutdown
Shutting down processing monitor
... shutting down processing monitor complete

**Comment by zerosansan** [comment]
Are you using the same turtlebot3 urdf gazebo files from my repository? The Lidar sensor seems to detect objects nearer than the set `min_scan_range` in the config.

**Comment by liwenshulws** [comment]
Yes, I have tried many times. But the robot still resets from the beginning when it encounters the first obstacle.

**Comment by zerosansan** [comment]
This is strange. What are your PC specs? You can try to increase the sleep time after `observation = env.reset()` in start_td3_training.py. Maybe it needs more time for Gazebo to reset your agent's position. Currently, it's been tested with `time.sleep(0.1)`.

**Comment by zerosansan** [comment]
Hi. I've updated the repository with some improvements to make the robot learn better. Feel free to try to test them out.

**Comment by liwenshulws** [comment]
Hello, I have used your updated code again, but I am running roslaunch turbobot3_ Rl_ Sim start_ Td3_ Training.launch
The following error occurred during: Traceback (most recent call last):
File "/home/robot/drl based maps crowd navigation with received risk/src/tourlebot3_rl_sim/src/start_td3_training. py", line 123, in<module>
Action=td3_ Trainer. act (state, step, add_noise=True)
File "/home/robot/drl based maps crowd navigation with received risk/src/tourlebot3_rl_sim/src/td3. py", line 206, in act
Action=self actor_ Local (state). cpu(). data. numpy() # deterministic action based on Actor's forward pass
File "/home/robot/miniconda3/envs/visualpy/lib/Python 2.7/site packages/torch/nn/modules/module. py", line 532, in__ Call__
Result=self. forward (* input, * * kwargs)
File "/home/robot/drl based maps crowd navigation with received risk/src/tourlebot3_rl_sim/src/td3. py", line 97, in forward
X=F.relu (self. linear1 (state))
File "/home/robot/miniconda3/envs/visualpy/lib/Python 2.7/site packages/torch/nn/modules/module. py", line 532, in__ Call__
Result=self. forward (* input, * * kwargs)
File "/home/robot/miniconda3/envs/visualpy/lib/Python 2.7/site packages/torch/nn/modules/linear. py", line 87, in forward
Return F.linear (input, self. weight, self. bias)
File "/home/robot/miniconda3/envs/visualpy/lib/Python 2.7/site packages/torch/nn/functional. py", line 1370, in line
Ret=torch. addmm (bias, input, weight. t())
RuntimeError: size mismatch, m1: [1 x 398], m2: [363 x 256] at/Pytoch/ten/src/TH/generic/THSensorMath. cpp: 136
[INFO] [1699930114.290257, 0.327000]: Stopping TurtleBot
[turbobot3_td3-1] process has died [pid 15535, exit code 1, cmd/home/robot/drl based maps crowd navigation with received risk/src/turbobot3_rl_sim/src/start_td3_training. py __ name:=turbobot3_td3 __ log:=/home/robot/ros/log/bf3d9262-8296-11ee-9711-000c29188fcd/turbobot3_td3-1. log]
Log file:/home/robot/. ros/log/bf3d9262-8296-11ee-9711-000c29188fcd/tourlebot3_ Td3-1 *. log

**Comment by liwenshulws** [comment]
Hello, I have run through your updated code again, but the robot always rotates in place and cannot reach the target point during training. What should I do?

**Comment by anShape** [comment]
> Hello, I have run through your updated code again, but the robot always rotates in place and cannot reach the target point during training. What should I do?

Hello sir, my issue are same as you
